[features]
seeds = false
[programs.localnet]
on_chain_twitter = "7cNGAP6tHh8W1BMxBEuMVfBUs8ogFT5PwUsENJLVhhjs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/abstracted/solana-wallet/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
